set(_TractographyTRX_CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/cmake")
list(PREPEND CMAKE_MODULE_PATH "${_TractographyTRX_CMAKE_MODULE_PATH}")
set(CMAKE_MODULE_PATH "${CMAKE_MODULE_PATH}" CACHE STRING "CMake module search path" FORCE)

option(TractographyTRX_FETCH_TRX_CPP "Fetch trx-cpp if not found" ON)
set(TRX_CPP_GIT_TAG "main" CACHE STRING "trx-cpp git tag")

find_package(trx-cpp QUIET)
if(NOT trx-cpp_FOUND)
  if(TractographyTRX_FETCH_TRX_CPP)
    if(NOT DEFINED TRX_BUILD_TESTS)
      set(TRX_BUILD_TESTS OFF CACHE BOOL "Build trx-cpp tests")
    endif()
    if(NOT DEFINED TRX_BUILD_EXAMPLES)
      set(TRX_BUILD_EXAMPLES OFF CACHE BOOL "Build trx-cpp examples")
    endif()
    if(NOT DEFINED TRX_BUILD_BENCHMARKS)
      set(TRX_BUILD_BENCHMARKS OFF CACHE BOOL "Build trx-cpp benchmarks")
    endif()
    if(CMAKE_VERSION VERSION_LESS 3.11)
      message(FATAL_ERROR "trx-cpp not found and CMake < 3.11 cannot fetch it. Set trx-cpp_DIR or update CMake.")
    endif()
    include(FetchContent)
    find_package(ZLIB QUIET)
    if(NOT ZLIB_FOUND AND ITK_DIR)
      set(_itk_zlib_include "${ITK_DIR}/Modules/ThirdParty/ZLIB/src")
      if(EXISTS "${_itk_zlib_include}/zlib.h")
        set(ZLIB_INCLUDE_DIR "${_itk_zlib_include}" CACHE PATH "ZLIB include dir" FORCE)
      endif()
      file(GLOB _itk_zlib_libs
        "${ITK_DIR}/lib/*zlib*"
        "${ITK_DIR}/Modules/ThirdParty/ZLIB/src/*zlib*"
        "${ITK_DIR}/Modules/ThirdParty/ZLIB/src/Release/*zlib*"
        "${ITK_DIR}/Modules/ThirdParty/ZLIB/src/Debug/*zlib*"
      )
      list(FILTER _itk_zlib_libs INCLUDE REGEX ".*\\.(lib|a|so|dylib)$")
      if(_itk_zlib_libs)
        list(GET _itk_zlib_libs 0 _itk_zlib_lib)
        set(ZLIB_LIBRARY "${_itk_zlib_lib}" CACHE FILEPATH "ZLIB library" FORCE)
      endif()
      unset(_itk_zlib_include)
      unset(_itk_zlib_libs)
      unset(_itk_zlib_lib)
      find_package(ZLIB QUIET)
    endif()
    if(NOT ZLIB_FOUND)
      message(FATAL_ERROR "ZLIB not found. Provide ZLIB_LIBRARY/ZLIB_INCLUDE_DIR or ensure ITK provides zlib.")
    endif()
    find_package(libzip QUIET)
    if(NOT libzip_FOUND)
      message(STATUS "libzip not found; fetching v1.11.4")
      if(NOT DEFINED LIBZIP_DO_INSTALL)
        set(LIBZIP_DO_INSTALL ON CACHE BOOL "Enable libzip package config")
      endif()
      if(NOT DEFINED BUILD_TOOLS)
        set(BUILD_TOOLS OFF CACHE BOOL "Disable libzip tools")
      endif()
      if(NOT DEFINED BUILD_REGRESS)
        set(BUILD_REGRESS OFF CACHE BOOL "Disable libzip regression tests")
      endif()
      if(NOT DEFINED BUILD_EXAMPLES)
        set(BUILD_EXAMPLES OFF CACHE BOOL "Disable libzip examples")
      endif()
      if(NOT DEFINED BUILD_DOC)
        set(BUILD_DOC OFF CACHE BOOL "Disable libzip docs")
      endif()
      FetchContent_Declare(
        libzip
        GIT_REPOSITORY https://github.com/nih-at/libzip.git
        GIT_TAG v1.11.4
      )
      FetchContent_MakeAvailable(libzip)
    endif()
    if(ITK_SOURCE_DIR AND EXISTS "${ITK_SOURCE_DIR}/Modules/ThirdParty/Eigen3/src/itkeigen/Eigen/Dense")
      set(EIGEN3_INCLUDE_DIR "${ITK_SOURCE_DIR}/Modules/ThirdParty/Eigen3/src/itkeigen" CACHE PATH "Eigen3 include dir")
      set(Eigen3_ROOT "${EIGEN3_INCLUDE_DIR}" CACHE PATH "Eigen3 root dir")
    elseif(ITK_DIR AND EXISTS "${ITK_DIR}/Modules/ThirdParty/Eigen3/src/itkeigen/Eigen/Dense")
      set(EIGEN3_INCLUDE_DIR "${ITK_DIR}/Modules/ThirdParty/Eigen3/src/itkeigen" CACHE PATH "Eigen3 include dir")
      set(Eigen3_ROOT "${EIGEN3_INCLUDE_DIR}" CACHE PATH "Eigen3 root dir")
    elseif(ITK_DIR)
      get_filename_component(_itk_build_parent "${ITK_DIR}" DIRECTORY)
      set(_itk_source_candidate "${_itk_build_parent}/ITK")
      if(EXISTS "${_itk_source_candidate}/Modules/ThirdParty/Eigen3/src/itkeigen/Eigen/Dense")
        set(EIGEN3_INCLUDE_DIR "${_itk_source_candidate}/Modules/ThirdParty/Eigen3/src/itkeigen" CACHE PATH "Eigen3 include dir")
        set(Eigen3_ROOT "${EIGEN3_INCLUDE_DIR}" CACHE PATH "Eigen3 root dir")
      endif()
      unset(_itk_build_parent)
      unset(_itk_source_candidate)
    endif()
    if(EIGEN3_INCLUDE_DIR AND NOT TARGET Eigen3::Eigen)
      add_library(Eigen3::Eigen INTERFACE IMPORTED)
      set_target_properties(Eigen3::Eigen PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${EIGEN3_INCLUDE_DIR}"
      )
    endif()
    message(STATUS "trx-cpp not found; fetching ${TRX_CPP_GIT_TAG}")
    FetchContent_Declare(
      trx_cpp
      GIT_REPOSITORY https://github.com/tee-ar-ex/trx-cpp.git
      GIT_TAG ${TRX_CPP_GIT_TAG}
    )
    FetchContent_MakeAvailable(trx_cpp)
  else()
    find_package(trx-cpp REQUIRED)
  endif()
endif()

# When this module is loaded by an app, load trx-cpp too.
set(TractographyTRX_EXPORT_CODE_INSTALL "
find_package(trx-cpp REQUIRED)
")
set(TractographyTRX_EXPORT_CODE_BUILD "
if(NOT ITK_BINARY_DIR)
  find_package(trx-cpp REQUIRED)
endif()
")
